spring:
  application:
    name: versions-tools
  main:
    banner-mode: off
    
    
logging:
  level:
    ROOT: ERROR
    
info:
  app:
    name: ${spring.application.name}
    version: '@project.version@'
