name: Push Package Sources and Build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
      
jobs:
  push-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Testing
        run: |
           ./mvnw clean -PnativeTest test
      
    